server:
  port: 8883

spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
      enabled: true
    discovery:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    jersey:
      enabled: false
    service-url:
      defaultZone: http://localhost:8881/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info
